# Usa Node 18
FROM node:18-alpine

# Define a pasta de trabalho
WORKDIR /app

# Copia arquivos de dependências primeiro
COPY package*.json ./

# Instala todas as dependências (incluindo devDependencies)
RUN npm install

# Copia o restante do projeto
COPY . .

# Build do Vite
RUN npm run build

# Porta padrão do Vite preview
EXPOSE 4173

# Comando para rodar o app
CMD ["npm", "run", "preview"]

